export default {
  showFooter: false,
  isSidebarCompact: false,
  showIndex : true, 
  showBreadcrumb: false,
  mode: 'light',
  layout: 'side',
  splitMenu: true,
  isFooterAside: true,
  isSidebarFixed: true,
  isHeaderFixed: true,
  isUseTabsRouter: true,
  showHeader: true,
  brandTheme: '#0052D9',
};
